// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC5qXTpFk3g3cDjgNqakDvGyNcceeerLM',
    appId: '1:340270248548:web:953eaf6b92b32a4dc12571',
    messagingSenderId: '340270248548',
    projectId: 'qrcaffeteria',
    authDomain: 'qrcaffeteria.firebaseapp.com',
    storageBucket: 'qrcaffeteria.firebasestorage.app',
    measurementId: 'G-1CWV2KRTP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ49VceL_XrwgN_8xondbgyvjMGiG9i7w',
    appId: '1:340270248548:android:029985afcac89983c12571',
    messagingSenderId: '340270248548',
    projectId: 'qrcaffeteria',
    storageBucket: 'qrcaffeteria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsG4tx1SziYkEcWEXilof2dWneHBNT3K4',
    appId: '1:340270248548:ios:dfa60352ddc23c66c12571',
    messagingSenderId: '340270248548',
    projectId: 'qrcaffeteria',
    storageBucket: 'qrcaffeteria.firebasestorage.app',
    iosBundleId: 'com.example.module',
  );
}
